/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelcasestudy;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author WINDOWS
 */
public class ADMIN_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN_dashbard
     */
    public ADMIN_Dashboard() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/images/LOGO_favicon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        report_popup = new javax.swing.JPopupMenu();
        reservation_history = new javax.swing.JMenuItem();
        revenue_report = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        email_label1 = new javax.swing.JLabel();
        invalid1 = new javax.swing.JLabel();
        casa_logo = new javax.swing.JLabel();
        casa_name = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        sublabel = new javax.swing.JLabel();
        email_label3 = new javax.swing.JLabel();
        maint_sched = new javax.swing.JButton();
        room_type_management = new javax.swing.JButton();
        room_management = new javax.swing.JButton();
        resv_management = new javax.swing.JButton();
        user_management = new javax.swing.JButton();
        employee_management = new javax.swing.JButton();
        report_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        reservation_history.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        reservation_history.setForeground(new java.awt.Color(104, 72, 50));
        reservation_history.setText("Reservation History");
        report_popup.add(reservation_history);

        revenue_report.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        revenue_report.setForeground(new java.awt.Color(104, 72, 50));
        revenue_report.setText("Revenue Report");
        report_popup.add(revenue_report);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(237, 234, 233));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_label1.setBackground(new java.awt.Color(105, 73, 50));
        email_label1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        email_label1.setForeground(new java.awt.Color(105, 73, 50));
        email_label1.setText("Done working?");
        jPanel2.add(email_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 270, -1));

        invalid1.setBackground(new java.awt.Color(105, 73, 50));
        invalid1.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid1.setForeground(new java.awt.Color(123, 24, 24));
        invalid1.setToolTipText("");
        invalid1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(invalid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        casa_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/LOGO_topleft.png"))); // NOI18N
        casa_logo.setText("jLabel2");
        jPanel2.add(casa_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, -1));

        casa_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/TITLELOGO_brownsmall.png"))); // NOI18N
        casa_name.setText("jLabel1");
        jPanel2.add(casa_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 240, 50));

        jButton4.setBackground(new java.awt.Color(134, 97, 72));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Log Out");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 150, 40));

        sublabel.setBackground(new java.awt.Color(105, 73, 50));
        sublabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        sublabel.setForeground(new java.awt.Color(105, 73, 50));
        sublabel.setText("Live Luxuriously.");
        jPanel2.add(sublabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        email_label3.setBackground(new java.awt.Color(105, 73, 50));
        email_label3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        email_label3.setForeground(new java.awt.Color(105, 73, 50));
        email_label3.setText("Welcome to the Admin Dashboard!");
        jPanel2.add(email_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 280, -1));

        maint_sched.setBackground(new java.awt.Color(140, 100, 75));
        maint_sched.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        maint_sched.setForeground(new java.awt.Color(255, 255, 255));
        maint_sched.setText("Maintenance Scheduling");
        maint_sched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maint_schedActionPerformed(evt);
            }
        });
        jPanel2.add(maint_sched, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 330, 40));

        room_type_management.setBackground(new java.awt.Color(140, 100, 75));
        room_type_management.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        room_type_management.setForeground(new java.awt.Color(255, 255, 255));
        room_type_management.setText("Room Type Management");
        room_type_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_type_managementActionPerformed(evt);
            }
        });
        jPanel2.add(room_type_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 330, 40));

        room_management.setBackground(new java.awt.Color(140, 100, 75));
        room_management.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        room_management.setForeground(new java.awt.Color(255, 255, 255));
        room_management.setText("Room Management");
        room_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_managementActionPerformed(evt);
            }
        });
        jPanel2.add(room_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 330, 40));

        resv_management.setBackground(new java.awt.Color(140, 100, 75));
        resv_management.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        resv_management.setForeground(new java.awt.Color(255, 255, 255));
        resv_management.setText("Reservation Management");
        resv_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resv_managementActionPerformed(evt);
            }
        });
        jPanel2.add(resv_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 330, 40));

        user_management.setBackground(new java.awt.Color(140, 100, 75));
        user_management.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        user_management.setForeground(new java.awt.Color(255, 255, 255));
        user_management.setText("User Records");
        user_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_managementActionPerformed(evt);
            }
        });
        jPanel2.add(user_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 330, 40));

        employee_management.setBackground(new java.awt.Color(140, 100, 75));
        employee_management.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        employee_management.setForeground(new java.awt.Color(255, 255, 255));
        employee_management.setText("Employee Management");
        employee_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_managementActionPerformed(evt);
            }
        });
        jPanel2.add(employee_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 330, 40));

        report_btn.setBackground(new java.awt.Color(140, 100, 75));
        report_btn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        report_btn.setForeground(new java.awt.Color(255, 255, 255));
        report_btn.setText("Report Generation Module");
        report_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_btnActionPerformed(evt);
            }
        });
        jPanel2.add(report_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 330, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 760));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BG_NewAdminLogin.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -190, -1, -1));

        setSize(new java.awt.Dimension(1358, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void report_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_btnActionPerformed
        // TODO add your handling code here:
        report_popup.show(report_btn, 0, report_btn.getHeight());
    }//GEN-LAST:event_report_btnActionPerformed

    private void maint_schedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maint_schedActionPerformed
        // TODO add your handling code here:
        ADMIN_MaintenanceScheduling userloginmenu = new ADMIN_MaintenanceScheduling();
        this.setVisible(false);
        userloginmenu.setVisible(true);
    }//GEN-LAST:event_maint_schedActionPerformed

    private void room_type_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_type_managementActionPerformed
        // TODO add your handling code here:
        ADMIN_RoomTypeManagement userloginmenu = new ADMIN_RoomTypeManagement();
        this.setVisible(false);
        userloginmenu.setVisible(true);
    }//GEN-LAST:event_room_type_managementActionPerformed

    private void room_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_managementActionPerformed
        // TODO add your handling code here:
         ADMIN_room_management userloginmenu = new ADMIN_room_management();
        this.setVisible(false);
        userloginmenu.setVisible(true);
    }//GEN-LAST:event_room_managementActionPerformed

    private void resv_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resv_managementActionPerformed
        ADMIN_ReservationManagement userloginmenu = new ADMIN_ReservationManagement();
        this.setVisible(false);
        userloginmenu.setVisible(true);
    }//GEN-LAST:event_resv_managementActionPerformed

    private void user_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_managementActionPerformed

        ADMIN_usermanagement userloginmenu = new ADMIN_usermanagement();
        this.dispose();
        userloginmenu.setVisible(true);
    }//GEN-LAST:event_user_managementActionPerformed

    private void employee_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_managementActionPerformed
        ADMIN_EmployeeManagement userloginmenu = new ADMIN_EmployeeManagement();
        this.setVisible(false);
        userloginmenu.setVisible(true);
    }//GEN-LAST:event_employee_managementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(ADMIN_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(ADMIN_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(ADMIN_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ADMIN_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ADMIN_Dashboard().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ADMIN_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ADMIN_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ADMIN_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ADMIN_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casa_logo;
    private javax.swing.JLabel casa_name;
    private javax.swing.JLabel email_label1;
    private javax.swing.JLabel email_label3;
    private javax.swing.JButton employee_management;
    private javax.swing.JLabel invalid1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton maint_sched;
    private javax.swing.JButton report_btn;
    private javax.swing.JPopupMenu report_popup;
    private javax.swing.JMenuItem reservation_history;
    private javax.swing.JButton resv_management;
    private javax.swing.JMenuItem revenue_report;
    private javax.swing.JButton room_management;
    private javax.swing.JButton room_type_management;
    private javax.swing.JLabel sublabel;
    private javax.swing.JButton user_management;
    // End of variables declaration//GEN-END:variables
}
