/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelcasestudy;
import java.awt.Toolkit;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author WINDOWS
 */

public class User_Checkout_complete extends javax.swing.JFrame {
    
    /**
     * Creates new form login_menu
     */
    public User_Checkout_complete() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/images/LOGO_favicon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        returnbtn = new javax.swing.JButton();
        invalid_confirm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invalid_email = new javax.swing.JLabel();
        invalid_password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        casa_icon = new javax.swing.JLabel();
        addanother = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Casa de Los Tropicos"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 234, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnbtn.setBackground(new java.awt.Color(134, 97, 72));
        returnbtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        returnbtn.setForeground(new java.awt.Color(255, 255, 255));
        returnbtn.setText("RETURN");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 517, 160, 49));

        invalid_confirm.setBackground(new java.awt.Color(105, 73, 50));
        invalid_confirm.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_confirm.setForeground(new java.awt.Color(123, 24, 24));
        invalid_confirm.setToolTipText("");
        jPanel1.add(invalid_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 702, -1, -1));

        jLabel3.setBackground(new java.awt.Color(105, 73, 50));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 73, 50));
        jLabel3.setText("Thank you for joining us!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 437, -1, -1));

        invalid_email.setBackground(new java.awt.Color(105, 73, 50));
        invalid_email.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_email.setForeground(new java.awt.Color(123, 24, 24));
        invalid_email.setToolTipText("");
        jPanel1.add(invalid_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 485, 120, -1));

        invalid_password.setBackground(new java.awt.Color(105, 73, 50));
        invalid_password.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        invalid_password.setForeground(new java.awt.Color(123, 24, 24));
        invalid_password.setToolTipText("");
        jPanel1.add(invalid_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 545, 170, -1));

        jLabel5.setBackground(new java.awt.Color(105, 73, 50));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 73, 50));
        jLabel5.setText("Your booking is complete.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 403, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/TITLELOGO_brownbig.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 299, 390, 80));

        casa_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/LOGO_medium.png"))); // NOI18N
        casa_icon.setText("jLabel1");
        jPanel1.add(casa_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 119, 240, 180));

        addanother.setBackground(new java.awt.Color(134, 97, 72));
        addanother.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        addanother.setForeground(new java.awt.Color(255, 255, 255));
        addanother.setText("ADD ANOTHER ROOM");
        addanother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addanotherActionPerformed(evt);
            }
        });
        jPanel1.add(addanother, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 578, 253, 49));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 520, 760));

        setSize(new java.awt.Dimension(513, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        // TODO add your handling code here:
        USER_login_screen userlogin = new USER_login_screen();
        this.setVisible(false);
        userlogin.setVisible(true);
    }//GEN-LAST:event_returnbtnActionPerformed

    private void addanotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addanotherActionPerformed
        // TODO add your handling code here:
        User_room_selection roomselect = new User_room_selection();
        this.dispose();
        roomselect.setVisible(true);
    }//GEN-LAST:event_addanotherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            DBConnection bConnection = new DBConnection(); // Allows this JFrame to connect to database.
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(User_Checkout_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(User_Checkout_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(User_Checkout_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(User_Checkout_complete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new User_Checkout_complete().setVisible(true);
                }
            });
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User_Checkout_complete.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(User_Checkout_complete.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(User_Checkout_complete.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(User_Checkout_complete.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addanother;
    private javax.swing.JLabel casa_icon;
    private javax.swing.JLabel invalid_confirm;
    private javax.swing.JLabel invalid_email;
    private javax.swing.JLabel invalid_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returnbtn;
    // End of variables declaration//GEN-END:variables
}
