/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelcasestudy;

import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author WINDOWS
 */
public class USER_booking extends javax.swing.JFrame {
    
    int aducount, chicount, totalguests;
    /**
     * Creates new form USER_booking
     */
    public USER_booking() {
        UIManager.put("Button.arc", 20);
        initComponents();
        LocalDate today = LocalDate.now();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/images/LOGO_favicon.png")));
        Date dateNow = Date.from(today.atStartOfDay(ZoneId.systemDefault()).toInstant());
        datetoday.setDate(dateNow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        invalid_guests = new javax.swing.JLabel();
        datetoday = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chi = new javax.swing.JSpinner();
        adu = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(237, 234, 233));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(105, 73, 50));
        jLabel16.setText("Booking");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(134, 97, 72));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, 40));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 73, 50));
        jLabel1.setText("Children");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, -1));

        invalid_guests.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        invalid_guests.setForeground(new java.awt.Color(123, 24, 24));
        jPanel4.add(invalid_guests, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        datetoday.setEnabled(false);
        jPanel4.add(datetoday, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 20));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 73, 50));
        jLabel5.setText("Adults");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(105, 73, 50));
        jLabel6.setText("Date Today:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        chi.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        chi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chiStateChanged(evt);
            }
        });
        jPanel4.add(chi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, -1));

        adu.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        adu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aduStateChanged(evt);
            }
        });
        jPanel4.add(adu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(323, 361));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (totalguests < 17) {
            User_room_selection roomsel = new User_room_selection();
            this.dispose();
            roomsel.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chiStateChanged
        // TODO add your handling code here:
        guestcheck();
    }//GEN-LAST:event_chiStateChanged

    private void aduStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aduStateChanged
        // TODO add your handling code here:
        guestcheck();
    }//GEN-LAST:event_aduStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(USER_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(USER_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(USER_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(USER_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new USER_booking().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(USER_booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(USER_booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(USER_booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(USER_booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void guestcheck() {
        if (adu.getValue() != null) {
            aducount = (int) adu.getValue();
            if (chi.getValue() == null) {
                chicount = 0;
            } else {
                chicount = (int) chi.getValue();
            }
            
            totalguests = aducount + chicount;
            
        } else if (adu.getValue() == null) {
            totalguests = 0;
        }
        
        // Swaps the tabs based on total guests.
        if (totalguests <= 16) {
            invalid_guests.setText(null);
        } else if (totalguests > 16) {
            System.out.println("TOO MANY PEOPLE");
            invalid_guests.setText(totalguests + " is too many guests.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSpinner adu;
    public static javax.swing.JSpinner chi;
    public static com.toedter.calendar.JDateChooser datetoday;
    private javax.swing.JLabel invalid_guests;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
